### PR TITLE
First step of migration

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
- Adding Vaadin 10 dependencies in pom.xml
- Adding a temporary HelloWorld page to test Vaadin 10 Router
- Commenting out some V8 specific stuff for now (They will be replaced with V10 equivalent later)
- Removing extra configuration from vaadin-maven-plugin
- Removing access control for now (it will be added later to a proper place)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU66Ws8fdwB-fInNVw:-LGU66Ws8fdwB-fInNVx:b-9zume8) (no related file):*
Does this project have any tests that verifies the functionality ?
Does it behave in the same way as previous FW8 version?

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 20 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU567q-xh-WlKJ_lL0:-LGU567q-xh-WlKJ_lL1:b-hkkfdi) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L20)):*
> ```
> MyUI
> ```

I think `MyUI` shouldn't be needed.

In Flow `UI` instance shouldn't be normally created at all.
locale will be set automatically.
The title should be set differently.
I don't remember exact way but there should be a way.
Somehow via the annotation most likely.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java, line 25 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5k715Kdrm6H5mn2F:-LGU5k715Kdrm6H5mn2G:b-wz8091) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java#L25)):*
> ```
> //
> ```

Please remove all commented code.
There is no `Navigator` class  in Flow anyway.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java, line 50 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5tnY9OH8gjsPU3jR:-LGU5tnY9OH8gjsPU3jS:bfcvzxl) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java#L50)):*
> ```
> //        Page page = MyUI.get().getPage()
> ```

Remove this.
This is for navigator.
I don't know  whether you have a replacement for this but this code is obsolete anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Comment by mehdi-vaadin** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU66Ws8fdwB-fInNVw:-LGU6by41eZoxR-QJ_Uo:b-funkh5) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Does this project have any tests that verifies the functionality ?
Does it behave in the same way as previous FW8 version?
</blockquote></details>

It doesn't have any test in UI. Only some tests in backend module. It should behave the same way as far as Flow allows us; in some cases, there isn't an equivalent in Flow yet.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 20 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU567q-xh-WlKJ_lL0:-LGU7W9bEMw56hMKRCam:b-dvfvwe) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L20)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> MyUI
> ```

I think `MyUI` shouldn't be needed.

In Flow `UI` instance shouldn't be normally created at all.
locale will be set automatically.
The title should be set differently.
I don't remember exact way but there should be a way.
Somehow via the annotation most likely.


</blockquote></details>

I kept `MyUI` because Access Control must be done somewhere.
I will remove `setLocale`.
I will use `PageTitle` annotation to set title.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java, line 25 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5k715Kdrm6H5mn2F:-LGU8ILQ3FnIyJ0Nr7bF:b-r6ax8s) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> //
> ```

Please remove all commented code.
There is no `Navigator` class  in Flow anyway.

</blockquote></details>

In the first step, the application must show a Hello World page with Flow for us to make sure that Flow works. Then I need to replace those commented parts with proper Flow equivalent. So, I kept them for now.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java, line 50 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5tnY9OH8gjsPU3jR:-LGU9MN2AfMHLYpn0jAy:bdikith) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java#L50)):*
> Page page = MyUI.get().getPage()
Like the other commented part, it will be replaced. But, based on your comments, I think it's a good idea to add some TODOs to show the users that these parts are going to change in next steps.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Comment by mehdi-vaadin** [comment]
Review status: 17 of 21 files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 20 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU567q-xh-WlKJ_lL0:-LGUFBvHEfePjP19H6Q3:bnmkihh) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L20)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Please find some UiInitEvent or something like that. All Ui init logic should be there instead.
</blockquote></details>

For now, nothing remained in `init` method. If it's needed, I will find and use UiInitEvent.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 4 files at r3.
Review status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU66Ws8fdwB-fInNVw:-LGUQhQVEH5DWhfpzw4-:bfnv3ge) (no related file):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

It doesn't have any test in UI. Only some tests in backend module. It should behave the same way as far as Flow allows us; in some cases, there isn't an equivalent in Flow yet.
</blockquote></details>

I'm worry that I can't verify that.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 20 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU567q-xh-WlKJ_lL0:-LGUQw95641ZcBLqmeZD:b-5cbwab) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L20)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

For now, nothing remained in `init` method. If it's needed, I will find and use UiInitEvent.
</blockquote></details>

So you can just remove this Ui class, right?

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java, line 25 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5k715Kdrm6H5mn2F:-LGUR6g36Dd9_CQF4upr:bgqz80q) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java#L25)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

In the first step, the application must show a Hello World page with Flow for us to make sure that Flow works. Then I need to replace those commented parts with proper Flow equivalent. So, I kept them for now.
</blockquote></details>

The code has no sense in Flow . So I dont see a reason to keep the code. You may replace it with TODO. But normally we create a ticket and removes comments.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java, line 50 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5tnY9OH8gjsPU3jR:-LGURcgh5_xP0fJ7bwGW:b4pl6xa) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java#L50)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> Page page = MyUI.get().getPage()
Like the other commented part, it will be replaced. But, based on your comments, I think it's a good idea to add some TODOs to show the users that these parts are going to change in next steps.
</blockquote></details>

Without code please.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Comment by mehdi-vaadin** [comment]
Review status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU66Ws8fdwB-fInNVw:-LGUgcG56sP-_4j9mIyN:b-gcgl71) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I'm worry that I can't verify that.
</blockquote></details>

Based on the discussion with Pekka, it was decided to convert the code as it is step-by-step. It's not another demo for Flow; it is a migration example. It is a good idea to add enough tests to Flow version of Bookstore; but maybe not now and not in this repository, because the objective of this one is showing how to migrate from 8 to 10.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 20 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU567q-xh-WlKJ_lL0:-LGUcJw0BhVXkMVPRnB9:b-wt0hsx) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L20)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

So you can just remove this Ui class, right?
</blockquote></details>

We should control access somewhere. So, UI class sounds like a good candidate. Do you have any other suggestion?

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java, line 25 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5k715Kdrm6H5mn2F:-LGUe-lR3tcfcAFXMCUz:bw66xfu) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The code has no sense in Flow . So I dont see a reason to keep the code. You may replace it with TODO. But normally we create a ticket and removes comments.
</blockquote></details>

There is a class named `Menu` that is responsible for building a menu bar and we should keep it. Of course, there is no `Navigator` in Flow and it will be removed; but `Menu` class must be converted to be compatible with Flow.
Regarding keeping the comments, the idea is to show the steps of migration to users. In the first step, we may comment some lines in order to keep the code compilable and in the next steps we will take care of converting them. Here, because the parent class of `MyUI` is changed to V10 `UI` it can't be passed to the constructor of `Navigator` class. So, I commented this part for now.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java, line 50 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5tnY9OH8gjsPU3jR:-LGUhkue8Cet2qVs5y3c:bmgw8vj) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/crud/SampleCrudLogic.java#L50)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Without code please.
</blockquote></details>

The idea of keeping commented code is the same here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU66Ws8fdwB-fInNVw:-LGVmTnOElwDdf-7mNrZ:bpbeb1e) (no related file):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

Based on the discussion with Pekka, it was decided to convert the code as it is step-by-step. It's not another demo for Flow; it is a migration example. It is a good idea to add enough tests to Flow version of Bookstore; but maybe not now and not in this repository, because the objective of this one is showing how to migrate from 8 to 10.
</blockquote></details>

Sure.

But I cannot guarantee from the code review that the resulting application has the same feature set and behaves EXACTLY the same as the previous version. I see you are commenting out some parts and don't understand is it disabled functionality or it's implemented differently.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 20 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU567q-xh-WlKJ_lL0:-LGVkyGk5TXaKnShgiRt:bp8fxhu) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L20)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

We should control access somewhere. So, UI class sounds like a good candidate. Do you have any other suggestion?
</blockquote></details>

I don't know the code of this application (and don't really want to, too many duties, sorry).
We don't recommend to use `UI` instance at all.
And don't recommend customize it.

This is an outdated concept from FW8 where `UI` is an entry point into the application and ONE HAS TO EXTEND IT.

With flow there is no even need to know about `UI` and it's quite rare situation if you need to extend it.

The problem with custom `UI`:  you may quite easily break the router functionality via custom `UI` and then you will wonder why routing doesn't work.

Please try to think about the way of extracting access control out of `UI`.
You should try  to think in totally different manner than original FW8 based application.
Detect the usecases and try to find an object where access control may be stored.

If there is absolutely no other way then I'm OK with having this UI (actually I'm not OK but let it be).

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java, line 26 at r3](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGVmIC50k9i7a0RG8uv:-LGVmIC50k9i7a0RG8uw:b-86qjar) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/6ec86a600685c674b9873a7c23c4cd47417cd9f7/bookstore-starter-flow-ui/src/main/java/com/vaadin/MyUI.java#L26)):*
> ```
> protected void init(VaadinRequest vaadinRequest) {
> ```

This method definitely should be removed.
It's defined in the `UI` class already like tat.

---

*[bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java, line 25 at r2](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU5k715Kdrm6H5mn2F:-LGVmv_w4xp2LhKAaeBH:b-1g2x5r) ([raw file](https://github.com/vaadin/bookstore-starter-flow/blob/87196255a2c2fce9660ef9e44bc386a27e7e327f/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/MainScreen.java#L25)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

There is a class named `Menu` that is responsible for building a menu bar and we should keep it. Of course, there is no `Navigator` in Flow and it will be removed; but `Menu` class must be converted to be compatible with Flow.
Regarding keeping the comments, the idea is to show the steps of migration to users. In the first step, we may comment some lines in order to keep the code compilable and in the next steps we will take care of converting them. Here, because the parent class of `MyUI` is changed to V10 `UI` it can't be passed to the constructor of `Navigator` class. So, I commented this part for now.
</blockquote></details>

OK........

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Comment by denis-anisimov** [comment]
As I side note: please be aware that I don't really know anything about the purpose of the task that you are doing.
I'm trying to review this PR as any other PR for a Flow based application.

So my comments kind of strict because that's the way how we are doing usually.
Since this project has educational purpose there can be agreements or assumptions which I'm not aware and sure.

---

Review status: all files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-:-LGVp7Ov2-V7pxyckNn-:b-qwysar)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7#-LGU66Ws8fdwB-fInNVw:-LGVsCvk0DPdRSzt49rb:b-uq7s2b) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Sure.

But I cannot guarantee from the code review that the resulting application has the same feature set and behaves EXACTLY the same as the previous version. I see you are commenting out some parts and don't understand is it disabled functionality or it's implemented differently.
</blockquote></details>

May be we should just collect shomehow parts which are not working in the same way in Flow version at the moment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/bookstore-starter-flow/7)*

**Pull request merged**
